title: "Qufe Theme"
name: "Qufe"
email: metinzorlu@msn.com 
description: Hello, welcome to my site! My areas of interest are theme making, graphic design and website development.
footer_desc: Personal web site

baseurl: "" 
url: "" 
paginate: 5

twitter_username: 
facebook_username: 
pinterest_username: 
github_username:  
youtube_username: 

image:
  kapak-0: assets/img/i-0.jpg
  kapak-1: assets/img/i-1.jpg
  kapak-2: assets/img/i-2.jpg
  kapak-3: assets/img/i-3.jpg

sass:
    style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
